name: Update EPG with Channel Removal

on:
  schedule:
    - cron: '0 2 * * *' # Jalankan setiap hari pukul 02:00 UTC
  workflow_dispatch: # Bisa dijalankan manual

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          pip install requests lxml

      # 4. Run Python script to merge and modify EPG
      - name: Run Python script to merge and modify EPG
        run: |
          python scripts/merge_epg.py  # Pastikan path ke skrip benar

      # 5. Commit and push merged file
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.merged_epg.xml,*.merged_epg.xml.gz"
          allowUpdates: true
          generateReleaseNotes: false
          replacesArtifacts: true
          removeArtifacts: true
          prerelease: false
          draft: false
          makeLatest: true
          tag: 1.0.0
